---
kind: pipeline
name: arm-build-deploy

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm run build
- name: publish
  image: plugins/gh-pages
  settings:
    ssh_key:
      from_secret: ssh_key
    upstream_name: git@github.com:bclindner/vue-trivia
    pages_directory: dist/
